# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_control.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_control(object):
    def setupUi(self, dialog_control):
        dialog_control.setObjectName("dialog_control")
        dialog_control.resize(948, 498)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog_control.sizePolicy().hasHeightForWidth())
        dialog_control.setSizePolicy(sizePolicy)
        self.gridLayout_6 = QtWidgets.QGridLayout(dialog_control)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(dialog_control)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_pole_zero_back = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pole_zero_back.sizePolicy().hasHeightForWidth())
        self.frame_pole_zero_back.setSizePolicy(sizePolicy)
        self.frame_pole_zero_back.setStyleSheet("border-color: rgb(170, 255, 127);\n"
"")
        self.frame_pole_zero_back.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pole_zero_back.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pole_zero_back.setLineWidth(2)
        self.frame_pole_zero_back.setMidLineWidth(2)
        self.frame_pole_zero_back.setObjectName("frame_pole_zero_back")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_pole_zero_back)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_lead_back = QtWidgets.QCheckBox(self.frame_pole_zero_back)
        self.checkBox_lead_back.setObjectName("checkBox_lead_back")
        self.gridLayout_3.addWidget(self.checkBox_lead_back, 0, 0, 1, 2)
        self.edit_tau_zero_back = QtWidgets.QDoubleSpinBox(self.frame_pole_zero_back)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_tau_zero_back.sizePolicy().hasHeightForWidth())
        self.edit_tau_zero_back.setSizePolicy(sizePolicy)
        self.edit_tau_zero_back.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_tau_zero_back.setDecimals(3)
        self.edit_tau_zero_back.setProperty("value", 1.0)
        self.edit_tau_zero_back.setObjectName("edit_tau_zero_back")
        self.gridLayout_3.addWidget(self.edit_tau_zero_back, 1, 1, 1, 1)
        self.label_tau_pole_back = QtWidgets.QLabel(self.frame_pole_zero_back)
        self.label_tau_pole_back.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tau_pole_back.setObjectName("label_tau_pole_back")
        self.gridLayout_3.addWidget(self.label_tau_pole_back, 2, 0, 1, 1)
        self.label_tau_zero_back = QtWidgets.QLabel(self.frame_pole_zero_back)
        self.label_tau_zero_back.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tau_zero_back.setObjectName("label_tau_zero_back")
        self.gridLayout_3.addWidget(self.label_tau_zero_back, 1, 0, 1, 1)
        self.edit_tau_pole_back = QtWidgets.QDoubleSpinBox(self.frame_pole_zero_back)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_tau_pole_back.sizePolicy().hasHeightForWidth())
        self.edit_tau_pole_back.setSizePolicy(sizePolicy)
        self.edit_tau_pole_back.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_tau_pole_back.setDecimals(3)
        self.edit_tau_pole_back.setProperty("value", 1.0)
        self.edit_tau_pole_back.setObjectName("edit_tau_pole_back")
        self.gridLayout_3.addWidget(self.edit_tau_pole_back, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_pole_zero_back, 3, 2, 1, 1)
        self.frame_pole_zero_fwd = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pole_zero_fwd.sizePolicy().hasHeightForWidth())
        self.frame_pole_zero_fwd.setSizePolicy(sizePolicy)
        self.frame_pole_zero_fwd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pole_zero_fwd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pole_zero_fwd.setObjectName("frame_pole_zero_fwd")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_pole_zero_fwd)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_lead_fwd = QtWidgets.QCheckBox(self.frame_pole_zero_fwd)
        self.checkBox_lead_fwd.setObjectName("checkBox_lead_fwd")
        self.gridLayout_2.addWidget(self.checkBox_lead_fwd, 0, 0, 1, 2)
        self.label_tau_pole_fwd = QtWidgets.QLabel(self.frame_pole_zero_fwd)
        self.label_tau_pole_fwd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tau_pole_fwd.setObjectName("label_tau_pole_fwd")
        self.gridLayout_2.addWidget(self.label_tau_pole_fwd, 2, 0, 1, 1)
        self.edit_tau_zero_fwd = QtWidgets.QDoubleSpinBox(self.frame_pole_zero_fwd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_tau_zero_fwd.sizePolicy().hasHeightForWidth())
        self.edit_tau_zero_fwd.setSizePolicy(sizePolicy)
        self.edit_tau_zero_fwd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_tau_zero_fwd.setDecimals(3)
        self.edit_tau_zero_fwd.setProperty("value", 1.0)
        self.edit_tau_zero_fwd.setObjectName("edit_tau_zero_fwd")
        self.gridLayout_2.addWidget(self.edit_tau_zero_fwd, 1, 1, 1, 1)
        self.edit_tau_pole_fwd = QtWidgets.QDoubleSpinBox(self.frame_pole_zero_fwd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_tau_pole_fwd.sizePolicy().hasHeightForWidth())
        self.edit_tau_pole_fwd.setSizePolicy(sizePolicy)
        self.edit_tau_pole_fwd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_tau_pole_fwd.setDecimals(3)
        self.edit_tau_pole_fwd.setProperty("value", 1.0)
        self.edit_tau_pole_fwd.setObjectName("edit_tau_pole_fwd")
        self.gridLayout_2.addWidget(self.edit_tau_pole_fwd, 2, 1, 1, 1)
        self.label_tau_zero_fwd = QtWidgets.QLabel(self.frame_pole_zero_fwd)
        self.label_tau_zero_fwd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tau_zero_fwd.setObjectName("label_tau_zero_fwd")
        self.gridLayout_2.addWidget(self.label_tau_zero_fwd, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_pole_zero_fwd, 2, 2, 1, 1)
        self.frame_kp = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_kp.sizePolicy().hasHeightForWidth())
        self.frame_kp.setSizePolicy(sizePolicy)
        self.frame_kp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_kp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_kp.setObjectName("frame_kp")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_kp)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_kp = QtWidgets.QLabel(self.frame_kp)
        self.label_kp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_kp.setObjectName("label_kp")
        self.gridLayout_7.addWidget(self.label_kp, 1, 0, 1, 1)
        self.edit_kp = QtWidgets.QDoubleSpinBox(self.frame_kp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_kp.sizePolicy().hasHeightForWidth())
        self.edit_kp.setSizePolicy(sizePolicy)
        self.edit_kp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_kp.setDecimals(3)
        self.edit_kp.setMinimum(-9999.0)
        self.edit_kp.setMaximum(9999.99)
        self.edit_kp.setObjectName("edit_kp")
        self.gridLayout_7.addWidget(self.edit_kp, 1, 1, 1, 1)
        self.ctrl_main_use = QtWidgets.QCheckBox(self.frame_kp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctrl_main_use.sizePolicy().hasHeightForWidth())
        self.ctrl_main_use.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(153, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.ctrl_main_use.setPalette(palette)
        self.ctrl_main_use.setAutoFillBackground(False)
        self.ctrl_main_use.setChecked(False)
        self.ctrl_main_use.setObjectName("ctrl_main_use")
        self.gridLayout_7.addWidget(self.ctrl_main_use, 0, 0, 1, 2)
        self.ctrl_pm_pi_check = QtWidgets.QCheckBox(self.frame_kp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctrl_pm_pi_check.sizePolicy().hasHeightForWidth())
        self.ctrl_pm_pi_check.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(153, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.ctrl_pm_pi_check.setPalette(palette)
        self.ctrl_pm_pi_check.setAutoFillBackground(False)
        self.ctrl_pm_pi_check.setChecked(False)
        self.ctrl_pm_pi_check.setObjectName("ctrl_pm_pi_check")
        self.gridLayout_7.addWidget(self.ctrl_pm_pi_check, 2, 0, 1, 2)
        self.gridLayout_5.addWidget(self.frame_kp, 2, 1, 1, 1)
        self.frame_integrator = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_integrator.sizePolicy().hasHeightForWidth())
        self.frame_integrator.setSizePolicy(sizePolicy)
        self.frame_integrator.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_integrator.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_integrator.setObjectName("frame_integrator")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_integrator)
        self.formLayout_2.setObjectName("formLayout_2")
        self.checkBox_integrator_use = QtWidgets.QCheckBox(self.frame_integrator)
        self.checkBox_integrator_use.setObjectName("checkBox_integrator_use")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.checkBox_integrator_use)
        self.label_tau_i = QtWidgets.QLabel(self.frame_integrator)
        self.label_tau_i.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tau_i.setObjectName("label_tau_i")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_tau_i)
        self.edit_tau_i = QtWidgets.QDoubleSpinBox(self.frame_integrator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_tau_i.sizePolicy().hasHeightForWidth())
        self.edit_tau_i.setSizePolicy(sizePolicy)
        self.edit_tau_i.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_tau_i.setDecimals(3)
        self.edit_tau_i.setProperty("value", 1.0)
        self.edit_tau_i.setObjectName("edit_tau_i")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_tau_i)
        self.label_integrator_limit = QtWidgets.QLabel(self.frame_integrator)
        self.label_integrator_limit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_integrator_limit.setObjectName("label_integrator_limit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_integrator_limit)
        self.edit_integrator_limit = QtWidgets.QDoubleSpinBox(self.frame_integrator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_integrator_limit.sizePolicy().hasHeightForWidth())
        self.edit_integrator_limit.setSizePolicy(sizePolicy)
        self.edit_integrator_limit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_integrator_limit.setDecimals(3)
        self.edit_integrator_limit.setMaximum(9999.99)
        self.edit_integrator_limit.setProperty("value", 1.0)
        self.edit_integrator_limit.setObjectName("edit_integrator_limit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_integrator_limit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.gridLayout_5.addWidget(self.frame_integrator, 2, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 4, 2, 1, 1)
        self.frame_out_limit = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_out_limit.sizePolicy().hasHeightForWidth())
        self.frame_out_limit.setSizePolicy(sizePolicy)
        self.frame_out_limit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_out_limit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_out_limit.setObjectName("frame_out_limit")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_out_limit)
        self.formLayout_3.setObjectName("formLayout_3")
        self.checkBox_out_limit = QtWidgets.QCheckBox(self.frame_out_limit)
        self.checkBox_out_limit.setObjectName("checkBox_out_limit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.checkBox_out_limit)
        self.label_out_limit = QtWidgets.QLabel(self.frame_out_limit)
        self.label_out_limit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_out_limit.setObjectName("label_out_limit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_out_limit)
        self.edit_output_limit_min = QtWidgets.QDoubleSpinBox(self.frame_out_limit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_output_limit_min.sizePolicy().hasHeightForWidth())
        self.edit_output_limit_min.setSizePolicy(sizePolicy)
        self.edit_output_limit_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_output_limit_min.setMinimum(-100000.0)
        self.edit_output_limit_min.setMaximum(100000.0)
        self.edit_output_limit_min.setProperty("value", -1.0)
        self.edit_output_limit_min.setObjectName("edit_output_limit_min")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_output_limit_min)
        self.edit_output_limit_max = QtWidgets.QDoubleSpinBox(self.frame_out_limit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_output_limit_max.sizePolicy().hasHeightForWidth())
        self.edit_output_limit_max.setSizePolicy(sizePolicy)
        self.edit_output_limit_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_output_limit_max.setMaximum(9999.99)
        self.edit_output_limit_max.setProperty("value", 1.0)
        self.edit_output_limit_max.setObjectName("edit_output_limit_max")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_output_limit_max)
        self.label_out_limit_2 = QtWidgets.QLabel(self.frame_out_limit)
        self.label_out_limit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_out_limit_2.setObjectName("label_out_limit_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_out_limit_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.gridLayout_5.addWidget(self.frame_out_limit, 3, 3, 1, 1)
        self.frame_pre_filter = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pre_filter.sizePolicy().hasHeightForWidth())
        self.frame_pre_filter.setSizePolicy(sizePolicy)
        self.frame_pre_filter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pre_filter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pre_filter.setObjectName("frame_pre_filter")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_pre_filter)
        self.gridLayout.setObjectName("gridLayout")
        self.edit_pre_tau_pole = QtWidgets.QDoubleSpinBox(self.frame_pre_filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_pre_tau_pole.sizePolicy().hasHeightForWidth())
        self.edit_pre_tau_pole.setSizePolicy(sizePolicy)
        self.edit_pre_tau_pole.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_pre_tau_pole.setDecimals(3)
        self.edit_pre_tau_pole.setProperty("value", 1.0)
        self.edit_pre_tau_pole.setObjectName("edit_pre_tau_pole")
        self.gridLayout.addWidget(self.edit_pre_tau_pole, 2, 1, 1, 1)
        self.edit_pre_tau_zero = QtWidgets.QDoubleSpinBox(self.frame_pre_filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_pre_tau_zero.sizePolicy().hasHeightForWidth())
        self.edit_pre_tau_zero.setSizePolicy(sizePolicy)
        self.edit_pre_tau_zero.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_pre_tau_zero.setDecimals(3)
        self.edit_pre_tau_zero.setProperty("value", 1.0)
        self.edit_pre_tau_zero.setObjectName("edit_pre_tau_zero")
        self.gridLayout.addWidget(self.edit_pre_tau_zero, 1, 1, 1, 1)
        self.label_pre_tau_zero = QtWidgets.QLabel(self.frame_pre_filter)
        self.label_pre_tau_zero.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pre_tau_zero.setObjectName("label_pre_tau_zero")
        self.gridLayout.addWidget(self.label_pre_tau_zero, 1, 0, 1, 1)
        self.checkBox_pre_use = QtWidgets.QCheckBox(self.frame_pre_filter)
        self.checkBox_pre_use.setObjectName("checkBox_pre_use")
        self.gridLayout.addWidget(self.checkBox_pre_use, 0, 0, 1, 2)
        self.label_pre_tau_pole = QtWidgets.QLabel(self.frame_pre_filter)
        self.label_pre_tau_pole.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pre_tau_pole.setObjectName("label_pre_tau_pole")
        self.gridLayout.addWidget(self.label_pre_tau_pole, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_pre_filter, 2, 0, 1, 1)
        self.frame_pre_filter_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pre_filter_2.sizePolicy().hasHeightForWidth())
        self.frame_pre_filter_2.setSizePolicy(sizePolicy)
        self.frame_pre_filter_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pre_filter_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pre_filter_2.setObjectName("frame_pre_filter_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_pre_filter_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_ff_use = QtWidgets.QCheckBox(self.frame_pre_filter_2)
        self.checkBox_ff_use.setObjectName("checkBox_ff_use")
        self.gridLayout_4.addWidget(self.checkBox_ff_use, 0, 0, 1, 2)
        self.label_ff_Kff = QtWidgets.QLabel(self.frame_pre_filter_2)
        self.label_ff_Kff.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_ff_Kff.setObjectName("label_ff_Kff")
        self.gridLayout_4.addWidget(self.label_ff_Kff, 1, 0, 1, 1)
        self.edit_ff_tau_zero = QtWidgets.QDoubleSpinBox(self.frame_pre_filter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_ff_tau_zero.sizePolicy().hasHeightForWidth())
        self.edit_ff_tau_zero.setSizePolicy(sizePolicy)
        self.edit_ff_tau_zero.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_ff_tau_zero.setDecimals(3)
        self.edit_ff_tau_zero.setProperty("value", 1.0)
        self.edit_ff_tau_zero.setObjectName("edit_ff_tau_zero")
        self.gridLayout_4.addWidget(self.edit_ff_tau_zero, 1, 2, 1, 1)
        self.edit_ff_Kff = QtWidgets.QDoubleSpinBox(self.frame_pre_filter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_ff_Kff.sizePolicy().hasHeightForWidth())
        self.edit_ff_Kff.setSizePolicy(sizePolicy)
        self.edit_ff_Kff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_ff_Kff.setDecimals(3)
        self.edit_ff_Kff.setProperty("value", 1.0)
        self.edit_ff_Kff.setObjectName("edit_ff_Kff")
        self.gridLayout_4.addWidget(self.edit_ff_Kff, 2, 0, 1, 1)
        self.checkBox_ff_use_filt = QtWidgets.QCheckBox(self.frame_pre_filter_2)
        self.checkBox_ff_use_filt.setObjectName("checkBox_ff_use_filt")
        self.gridLayout_4.addWidget(self.checkBox_ff_use_filt, 0, 2, 1, 1)
        self.edit_ff_tau_pole = QtWidgets.QDoubleSpinBox(self.frame_pre_filter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_ff_tau_pole.sizePolicy().hasHeightForWidth())
        self.edit_ff_tau_pole.setSizePolicy(sizePolicy)
        self.edit_ff_tau_pole.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_ff_tau_pole.setDecimals(3)
        self.edit_ff_tau_pole.setProperty("value", 1.0)
        self.edit_ff_tau_pole.setObjectName("edit_ff_tau_pole")
        self.gridLayout_4.addWidget(self.edit_ff_tau_pole, 2, 2, 1, 1)
        self.label_ff_tau_pole = QtWidgets.QLabel(self.frame_pre_filter_2)
        self.label_ff_tau_pole.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ff_tau_pole.setObjectName("label_ff_tau_pole")
        self.gridLayout_4.addWidget(self.label_ff_tau_pole, 2, 1, 1, 1)
        self.label_ff_tau_zero = QtWidgets.QLabel(self.frame_pre_filter_2)
        self.label_ff_tau_zero.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ff_tau_zero.setObjectName("label_ff_tau_zero")
        self.gridLayout_4.addWidget(self.label_ff_tau_zero, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_pre_filter_2, 3, 0, 1, 2)
        self.label_ID = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ID.sizePolicy().hasHeightForWidth())
        self.label_ID.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ID.setFont(font)
        self.label_ID.setTextFormat(QtCore.Qt.AutoText)
        self.label_ID.setObjectName("label_ID")
        self.gridLayout_5.addWidget(self.label_ID, 1, 0, 1, 2)
        self.label_ID_lead = QtWidgets.QLabel(self.frame)
        self.label_ID_lead.setObjectName("label_ID_lead")
        self.gridLayout_5.addWidget(self.label_ID_lead, 0, 0, 1, 2)
        self.gridLayout_6.addWidget(self.frame, 0, 0, 1, 3)
        self.pushButton_ctrlRetry = QtWidgets.QPushButton(dialog_control)
        self.pushButton_ctrlRetry.setObjectName("pushButton_ctrlRetry")
        self.gridLayout_6.addWidget(self.pushButton_ctrlRetry, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(dialog_control)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_6.addWidget(self.buttonBox, 1, 2, 1, 1)
        self.pushButton_ctrlIniLoad = QtWidgets.QPushButton(dialog_control)
        self.pushButton_ctrlIniLoad.setObjectName("pushButton_ctrlIniLoad")
        self.gridLayout_6.addWidget(self.pushButton_ctrlIniLoad, 1, 1, 1, 1)

        self.retranslateUi(dialog_control)
        self.buttonBox.accepted.connect(dialog_control.accept)
        self.buttonBox.rejected.connect(dialog_control.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog_control)
        dialog_control.setTabOrder(self.ctrl_main_use, self.checkBox_integrator_use)
        dialog_control.setTabOrder(self.checkBox_integrator_use, self.edit_tau_i)
        dialog_control.setTabOrder(self.edit_tau_i, self.edit_integrator_limit)
        dialog_control.setTabOrder(self.edit_integrator_limit, self.checkBox_lead_fwd)
        dialog_control.setTabOrder(self.checkBox_lead_fwd, self.edit_tau_zero_fwd)
        dialog_control.setTabOrder(self.edit_tau_zero_fwd, self.edit_tau_pole_fwd)
        dialog_control.setTabOrder(self.edit_tau_pole_fwd, self.checkBox_out_limit)
        dialog_control.setTabOrder(self.checkBox_out_limit, self.edit_output_limit_min)
        dialog_control.setTabOrder(self.edit_output_limit_min, self.checkBox_pre_use)
        dialog_control.setTabOrder(self.checkBox_pre_use, self.edit_pre_tau_zero)
        dialog_control.setTabOrder(self.edit_pre_tau_zero, self.edit_pre_tau_pole)
        dialog_control.setTabOrder(self.edit_pre_tau_pole, self.checkBox_lead_back)
        dialog_control.setTabOrder(self.checkBox_lead_back, self.edit_tau_zero_back)
        dialog_control.setTabOrder(self.edit_tau_zero_back, self.edit_tau_pole_back)
        dialog_control.setTabOrder(self.edit_tau_pole_back, self.buttonBox)

    def retranslateUi(self, dialog_control):
        _translate = QtCore.QCoreApplication.translate
        dialog_control.setWindowTitle(_translate("dialog_control", "Dialog"))
        self.frame_pole_zero_back.setToolTip(_translate("dialog_control", "<html><head/><body><p>A first order filter with a pole and a zero.</p><p>The DC gain is 1 in any case (lead or lag configration.</p><p>Transfer function is:</p><p>G(s) = (tau_zero s + 1)/(tau_pole s + 1)</p></body></html>"))
        self.checkBox_lead_back.setToolTip(_translate("dialog_control", "<html><head/><body><p>Enable this part, to have a Lead-term (or lag) in the feedback branch.</p></body></html>"))
        self.checkBox_lead_back.setText(_translate("dialog_control", "Lead/lag in feed back"))
        self.label_tau_pole_back.setText(_translate("dialog_control", "Tau_pole"))
        self.label_tau_zero_back.setText(_translate("dialog_control", "Tau_zero"))
        self.frame_pole_zero_fwd.setToolTip(_translate("dialog_control", "<html><head/><body><p>A first order filter with a pole and a zero.</p><p>The DC gain is 1 in any case (lead or lag configration.</p><p>Transfer function is:</p><p>G(s) = (tau_zero s + 1)/(tau_pole s + 1)</p><p><br/></p></body></html>"))
        self.checkBox_lead_fwd.setText(_translate("dialog_control", "Lead/lag in forward"))
        self.label_tau_pole_fwd.setText(_translate("dialog_control", "Tau_pole"))
        self.label_tau_zero_fwd.setText(_translate("dialog_control", "Tau_zero"))
        self.frame_kp.setToolTip(_translate("dialog_control", "<html><head/><body><p>If not enabled, then no part of this controller is enabled.</p><p>Proportional gain Kp</p><p>Kp may be zero (e.g. if feed forward is used only to get open loop functionality)</p></body></html>"))
        self.label_kp.setText(_translate("dialog_control", "<html><head/><body><p><span style=\" font-weight:600;\">Kp</span></p></body></html>"))
        self.ctrl_main_use.setText(_translate("dialog_control", "Enable control"))
        self.ctrl_pm_pi_check.setText(_translate("dialog_control", "+/- PI check"))
        self.checkBox_integrator_use.setText(_translate("dialog_control", "Integrator"))
        self.label_tau_i.setText(_translate("dialog_control", "Tau_i"))
        self.label_integrator_limit.setText(_translate("dialog_control", "Limit"))
        self.edit_integrator_limit.setToolTip(_translate("dialog_control", "<html><head/><body><p>Symmetric around zero</p><p>In addition, if output limit is reached, then the integrator stops too.</p></body></html>"))
        self.frame_out_limit.setToolTip(_translate("dialog_control", "<html><head/><body><p>Output limit is symmetric around zero, and units follow the controller output units.</p></body></html>"))
        self.checkBox_out_limit.setText(_translate("dialog_control", "Output limit"))
        self.label_out_limit.setText(_translate("dialog_control", "min"))
        self.label_out_limit_2.setText(_translate("dialog_control", "max"))
        self.label_pre_tau_zero.setText(_translate("dialog_control", "Tau_zero"))
        self.checkBox_pre_use.setText(_translate("dialog_control", "Pre filter"))
        self.label_pre_tau_pole.setText(_translate("dialog_control", "Tau_pole"))
        self.checkBox_ff_use.setText(_translate("dialog_control", "Feed forward"))
        self.label_ff_Kff.setText(_translate("dialog_control", "Kff"))
        self.checkBox_ff_use_filt.setText(_translate("dialog_control", "filter"))
        self.label_ff_tau_pole.setText(_translate("dialog_control", "Tau_pole"))
        self.label_ff_tau_zero.setText(_translate("dialog_control", "Tau_zero"))
        self.label_ID.setText(_translate("dialog_control", "<html><head/><body><p><span style=\" font-weight:600; color:#990000;\">Roll velocity</span></p></body></html>"))
        self.label_ID_lead.setText(_translate("dialog_control", "Controller parameters"))
        self.pushButton_ctrlRetry.setToolTip(_translate("dialog_control", "Request parameters from robot - discarding any unsaved changes."))
        self.pushButton_ctrlRetry.setText(_translate("dialog_control", "Load from robot"))
        self.pushButton_ctrlIniLoad.setToolTip(_translate("dialog_control", "<html><head/><body><p>Load parameters from ini-file (regbot.ini)</p></body></html>"))
        self.pushButton_ctrlIniLoad.setText(_translate("dialog_control", "Load from ini"))
